name: Lint

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: xt0rted/markdownlint-problem-matcher@v1
    - name: Lint markdown
      run: markdownlint **/*.md --ignore node_modules
